### PR TITLE
Improved the shell scripts

### PR DESCRIPTION
**Pull request by proffapt**
Scripts will be more
- aesthetic, code wise
- robust, logically
- descriptive, with colored logs

### CODE REVIEW

**Comment by proffapt** [comment]
TODO:
- [ ] Better logging
- [ ] Robustness - setup script

**Comment by proffapt** [comment]
@sheharyaar review crow

**Comment by sheharyaar** [comment]
pi pe test kiya?

**Comment by proffapt** [comment]
> pi pe test kiya?

Hub down hojayega :looksaway:

**Review by sheharyaar — APPROVED** [review]
LGTM

**Pull request merged**
